### ISSUE TITLE
Sails server initaliztion failed

### ISSUE THREAD

**Issue by kavesh** [aronluigi/sails-cbes#6]
Hi
I am getting following error while starting the sails server,
The version used for development
Node - 5.0
Sails - 0.11.3
sails-cbes - 0.1.16
couchbase - 4.1.0

Following is the error

```
error: There was an error attempting to require("sails-cbes")
error: Is this a valid Sails/Waterline adapter?  The following error was encountered ::
error: Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at bindings (/home/user/TestCouchbase/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/TestCouchbase/node_modules/couchbase/lib/binding.js:127:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/user/TestCouchbase/node_modules/couchbase/lib/couchbase.js:3:15)
    at Module._compile (module.js:410:26) [Error: Module version mismatch. Expected 46, got 47.]
```

Following is connection.js

```
sailsCbes: {
      //couchbase
    adapter: 'sails-cbes',
      cb: {
        host: 'localhost',
        port: 8091,
        user: 'user',
        pass: 'user',
        operationTimeout: 60 * 1000, // 60s
        bucket: {
          name: 'TestData',
          pass: 'user'
        }
      },
      //elasticsearch
      es: {
        host: ['127.0.0.1:9200'],
        log: 'error',
        index: 'testdata',
        numberOfShards: 5,
        requestTimeout: 30000,
        numberOfReplicas: 1
      }
  },
```

Help here would be much appreciated, Thanks in advance

**Comment by aronluigi** [comment]
I will have a look as soon as possible. Thank you for reporting this problem!
